### ISSUE TITLE
[BUG] Rote Pfeile werden angezeigt, selbst wenn nicht genug Content zum Scrollen vorhanden ist

### ISSUE THREAD

**Issue by DanHubGitHub** [Bergflix-Remake/frontend#144]
# Bug Report
## Summary ✏️
Wenn man auf der Homepage herunterscrollt, sieht man bei Kategorien, in denen man nicht (horizontal) scrollen kann, dennoch die Roten Pfeile links und rechts. Dasselbe gilt für Kategorien in denen es zwar rechts genug Content gäbe, der Prozess nach Links zu scrollen aber sinnlos ist da links die "Wand" ist. Ich denke der Knopf links sollte erst auftauchen, wenn man in einer Kategorie mindestens einmal nach rechts gescrollt hat.
## Reproduction 🔃
1. Go to 'www.dev.bergflix.de'
2. Scroll down to 'Serien"
3. See error
4. Victory

## Screenshots 📷
![grafik](https://user-images.githubusercontent.com/118742562/223447261-2b0b3ddb-ca7d-440b-974c-a01ec358c655.png)

**Comment by AnnikenYT** [comment]
closed in 42652db
