### ISSUE TITLE
[BUG] Header overlaps with the text beneath it

### ISSUE THREAD

**Issue by Mondmarmelade** [Bergflix-Remake/frontend#154]
# Bug Report
## Summary ✏️
Header overlaps with the text beneath it.

## Reproduction 🔃
1. Go to https://bergflix.de/legal

## Expected Behavior 🧪
Padding at the top of the page could solve the problem.

## Screenshots 📷
![grafik](https://user-images.githubusercontent.com/91614367/227733679-9e09d3f4-404a-4a84-aa10-af510007e87d.png)

**Comment by vednp** [comment]
Hey @Mondmarmelade Can you assign it to me?
