### ISSUE TITLE
[BUG] Watchpage offset visual bug

### ISSUE THREAD

**Issue by Mondmarmelade** [Bergflix-Remake/frontend#91]
# Bug Report
## Summary ✏️
The playlist on the watchpage generates an offset under the player.

## Reproduction 🔃
1. Go to 'https://dev.bergflix.de/watch/7'

## Expected Behavior 🧪
The playlist should have a defined height so that it prevents offsets and cuts off the overflow instead.

## Screenshots 📷
![Screenshot 2022-10-16 141536](https://user-images.githubusercontent.com/91614367/196034964-2e07faaf-63f3-4cc4-a7bf-47f03bae4da5.jpg)

**Comment by AnnikenYT** [comment]
Fixed in https://github.com/Bergflix-Remake/frontend/commit/73e2ee9b7e11805ef61c8c4f618a727de996d227
